name: sera
description: SERA – Service & Equipment Repair Assistant (Flutter)
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

# Flutter config
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - sera_logo/
    # Lägg till dina assets här vid behov:
    # - assets/images/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / tema
  google_fonts: ^6.2.1

  # State & verktyg
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  printing: ^5.13.1
  flutter_markdown: ^0.6.18
  flutter_stripe: ^12.1.1
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "sera_logo/SERA6.png"
  remove_alpha_ios: true
