name: sera
description: SERA – Service & Equipment Repair Assistant (Flutter)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

# Flutter config
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - sera_logo/
    # Lägg till dina assets här vid behov:
    # - assets/images/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / tema
  google_fonts: ^6.2.1

  # State & verktyg
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
